import test from "node:test";
import assert from "node:assert/strict";
import { CastStore, GroupStore } from "../src/cast-group-store.js";
import { ProjectStore } from "../src/project-store.js";
class Memory { constructor(){this.data=new Map();} getItem(k){return this.data.get(k)||null;} setItem(k,v){this.data.set(k,v);} }
test("casts and groups keep explicit persona references and safe membership",()=>{const storage=new Memory(), casts=new CastStore(storage), groups=new GroupStore(storage);const cast=casts.create({name:"Main",personaRefs:[{type:"persona",id:"p1"},{type:"persona",id:"p1"}]});const group=groups.create({name:"Crew",type:"crew"});assert.deepEqual(cast.personaRefs,[{type:"persona",id:"p1"}]);casts.addPersona(cast.id,"p2");groups.addPersona(group.id,"p1");groups.addPersona(group.id,"p1");assert.equal(casts.open(cast.id).personaRefs.length,2);assert.equal(groups.open(group.id).personaRefs.length,1);assert.equal(casts.open(cast.id).personaRefs[0].persona,undefined);});
test("collections allow missing references, collision-safe imports, and preserve personas on delete",()=>{const storage=new Memory(), casts=new CastStore(storage), groups=new GroupStore(storage);const cast=casts.create({id:"cast_main",name:"Main",personaRefs:[{type:"persona",id:"missing"}]});assert.equal(casts.diagnostics([],[]).missingPersonaReferences,1);const imported=casts.importBrowserData({casts:[cast]});assert.equal(imported.imported,1);assert.notEqual(imported.idMap.cast_main,"cast_main");assert.equal(casts.delete(cast.id),true);assert.equal(groups.create({name:"Empty"}).personaRefs.length,0);});
test("project references import with remapped collection ids",()=>{const storage=new Memory(), projects=new ProjectStore(storage), casts=new CastStore(storage);const project=projects.create({name:"P",castRefs:[{type:"cast",id:"cast_old"}]});const result=casts.importBrowserData({casts:[{id:"cast_old",name:"C",projectRef:{type:"project",id:project.id},personaRefs:[]}]},{projectMap:{[project.id]:"project_new"}});assert.equal(result.imported,1);assert.equal(casts.all()[0].projectRef.id,"project_new");assert.equal(project.castRefs[0].id,"cast_old");});
test("membership is composable, edits keep ids, and project-only personas remain valid",()=>{const storage=new Memory(), casts=new CastStore(storage), groups=new GroupStore(storage), projects=new ProjectStore(storage);const project=projects.create({name:"P",personaRefs:[{type:"persona",id:"p3"}]});const a=casts.create({name:"A"}), b=casts.create({name:"B"}), g1=groups.create({name:"G1"}), g2=groups.create({name:"G2"});casts.addPersona(a.id,"p1");casts.addPersona(b.id,"p1");groups.addPersona(g1.id,"p1");groups.addPersona(g2.id,"p1");const before=a.id;casts.update(a.id,{name:"Renamed"});assert.equal(casts.open(a.id).id,before);assert.equal(casts.open(b.id).personaRefs[0].id,"p1");assert.equal(groups.open(g2.id).personaRefs[0].id,"p1");casts.removePersona(a.id,"p1");assert.equal(casts.open(a.id).personaRefs.length,0);assert.equal(projects.open(project.id).personaRefs[0].id,"p3");});
test("diagnostics inspect raw persisted duplicates and malformed references",()=>{const storage=new Memory(), casts=new CastStore(storage);storage.setItem("personaforge.casts.v1",JSON.stringify([{schemaVersion:1,id:"cast_raw",name:"Raw",personaRefs:[{type:"persona",id:"p1"},{type:"persona",id:"p1"},{oops:true}]}]));const diagnostics=casts.diagnostics([{meta:{persona_id:"p1"}}],[]);assert.equal(diagnostics.duplicateMembershipReferences.length,1);assert.equal(diagnostics.invalidReferences,1);});
test("legacy snapshots without collections remain import-compatible",()=>{const storage=new Memory(), casts=new CastStore(storage);assert.equal(casts.importBrowserData({personas:[]}).imported,0);assert.deepEqual(casts.all(),[]);});
