import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { generatePersona } from "../src/generator.js";
import { PersonaController } from "../src/persona-controller.js";
import { affectedBy } from "../src/dependency-engine.js";

const paths={settings:"core/settings",eras:"core/eras",lifeStages:"core/life_stages",countries:"core/countries",species:"identity/species",heritage:"identity/heritage",givenNames:"identity/names/given_names",familyNames:"identity/names/family_names",traits:"personality/traits",flaws:"personality/flaws",values:"personality/values",habits:"personality/habits",quirks:"personality/quirks",hobbies:"lifestyle/hobbies",interests:"lifestyle/interests",occupations:"lifestyle/occupations",education:"lifestyle/education",housing:"lifestyle/housing",transport:"lifestyle/transport",hair:"appearance/hair",eyes:"appearance/eyes",body:"appearance/body",features:"appearance/features",clothingStyles:"clothing/styles",outfits:"clothing/signature_outfits",goals:"narrative/goals",secrets:"narrative/secrets",signatureItems:"narrative/signature_items",expressions:"narrative/expressions"};
async function load(){const result={};for(const [key,path] of Object.entries(paths))result[key]=JSON.parse(await readFile(new URL(`../data/${path}.json`,import.meta.url)));return result;}

test("dependency graph returns transitive affected fields",()=>{const affected=affectedBy("life.job");assert.ok(affected.includes("life.income_band"));assert.ok(affected.includes("life.housing"));});
test("field locks survive reroll unlocked",async()=>{const data=await load();const persona=generatePersona(data,{seed:"locks"});const controller=new PersonaController(data,persona);controller.toggleLock("personality.core");const core=persona.personality.core;controller.rerollUnlocked();assert.deepEqual(persona.personality.core,core);});
test("rerolled dependency marks downstream fields stale",async()=>{const data=await load();const persona=generatePersona(data,{seed:"stale",anchors:{life_stage:"adult"}});const controller=new PersonaController(data,persona);controller.rerollField("life.job");assert.ok(persona.state.stale_fields.includes("life.income_band"));controller.regenerateAffected();assert.deepEqual(persona.state.stale_fields,[]);});
test("locked field is not rerolled",async()=>{const data=await load();const persona=generatePersona(data,{seed:"locked"});const controller=new PersonaController(data,persona);controller.toggleLock("narrative.goal");const goal=persona.narrative.goal;assert.equal(controller.rerollField("narrative.goal"),false);assert.deepEqual(persona.narrative.goal,goal);});
test("primary reroll preserves locked secondary and tension roles",async()=>{const data=await load();const persona=generatePersona(data,{seed:"value-locks",valueCount:3});const controller=new PersonaController(data,persona);controller.toggleLock("personality.values.secondary");controller.toggleLock("personality.values.tension");const secondary=structuredClone(persona.personality.values.secondary),tension=structuredClone(persona.personality.values.tension);controller.rerollField("personality.values.primary");assert.deepEqual(persona.personality.values.secondary,secondary);assert.deepEqual(persona.personality.values.tension,tension);});
test("secondary and tension rerolls preserve upstream value roles",async()=>{const data=await load();const persona=generatePersona(data,{seed:"value-role-rerolls",valueCount:3});const controller=new PersonaController(data,persona);const primary=structuredClone(persona.personality.values.primary);controller.rerollField("personality.values.secondary");assert.deepEqual(persona.personality.values.primary,primary);assert.ok(persona.state.stale_fields.includes("personality.values.tension"));const secondary=structuredClone(persona.personality.values.secondary);controller.keepExisting();controller.rerollField("personality.values.tension");assert.deepEqual(persona.personality.values.primary,primary);assert.deepEqual(persona.personality.values.secondary,secondary);});
