import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { generatePersona } from "../src/generator.js";
import { alternativesFor } from "../src/controlled-alternatives.js";
import { PersonaController } from "../src/persona-controller.js";

const paths={settings:"core/settings",eras:"core/eras",lifeStages:"core/life_stages",countries:"core/countries",species:"identity/species",heritage:"identity/heritage",givenNames:"identity/names/given_names",familyNames:"identity/names/family_names",traits:"personality/traits",flaws:"personality/flaws",values:"personality/values",habits:"personality/habits",quirks:"personality/quirks",hobbies:"lifestyle/hobbies",interests:"lifestyle/interests",occupations:"lifestyle/occupations",education:"lifestyle/education",housing:"lifestyle/housing",transport:"lifestyle/transport",hair:"appearance/hair",eyes:"appearance/eyes",body:"appearance/body",features:"appearance/features",clothingStyles:"clothing/styles",outfits:"clothing/signature_outfits",goals:"narrative/goals",secrets:"narrative/secrets",signatureItems:"narrative/signature_items",expressions:"narrative/expressions"};
const load = async () => { const result={}; for(const [key,path] of Object.entries(paths)) result[key]=JSON.parse(await readFile(new URL(`../data/${path}.json`,import.meta.url))); result.versions={schema:"1.0",data:"0.1.0"}; return result; };
test("alternatives are deterministic, bounded, and exclude current value", async () => { const library=await load(); const persona=generatePersona(library,{seed:"alternatives",mode:"varied"}); const first=alternativesFor(library,persona,"life.job"); assert.deepEqual(first,alternativesFor(library,persona,"life.job")); assert.ok(first.alternatives.length<=4); assert.equal(first.alternatives.some(item=>item.id===first.current.id),false); });
test("unsupported and derived fields remain unavailable", async () => { const library=await load(); const persona=generatePersona(library,{seed:"unsupported"}); assert.equal(alternativesFor(library,persona,"life.experience_years").supported,false); assert.equal(alternativesFor(library,persona,"narrative.integration").supported,false); });
test("choosing an alternative mutates only the field and uses stale propagation", async () => { const library=await load(); const persona=generatePersona(library,{seed:"choose-alternative"}); const controller=new PersonaController(library,persona); const before=structuredClone(persona); const options=controller.alternatives("life.job"); assert.ok(options.alternatives.length); assert.equal(controller.chooseAlternative("life.job",options.alternatives[0].id),true); assert.notEqual(persona.life.job.id,before.life.job.id); assert.deepEqual(persona.foundation,before.foundation); assert.deepEqual(persona.interests,before.interests); assert.ok(persona.state.stale_fields.includes("life.career_level")); assert.equal(persona.state.selection_provenance["life.job"].origin,"user_alternative_choice"); });
test("locked fields reject controlled choices", async () => { const library=await load(); const persona=generatePersona(library,{seed:"locked-alternative"}); const controller=new PersonaController(library,persona); const options=controller.alternatives("life.job"); const before=structuredClone(persona.life.job); persona.state.locks["life.job"]=true; assert.equal(controller.chooseAlternative("life.job",options.alternatives[0].id),false); assert.deepEqual(persona.life.job,before); });
test("opening alternatives does not consume generation RNG", async () => { const library=await load(); const a=generatePersona(library,{seed:"rng-neutral"}); const b=structuredClone(a); const ca=new PersonaController(library,a); const cb=new PersonaController(library,b); ca.alternatives("life.job"); ca.rerollField("life.housing"); cb.rerollField("life.housing"); assert.deepEqual(a.life.housing,b.life.housing); });
