import test from "node:test";
import assert from "node:assert/strict";
import { libraryIndex, queryLibrary } from "../src/library-query.js";
const persona = (id, name, setting="modern") => ({ meta:{persona_id:id,created_at:`2024-01-0${id}`,modified_at:`2024-02-0${id}`}, origin:{name}, foundation:{setting:{id:setting,name:setting},species:{id:"human",name:"Human"},life_stage:{id:"adult",name:"Adult"},country:{id:"uk",name:"United Kingdom"}}, life:{job:{id:"baker",name:"Baker"}} });
const records = [
  {persona:persona("1","Vesper Reedwalker"),metadata:{favorite:true,tags:["protagonist"],archived:false,updatedAt:"2024-03-01",createdAt:"2024-01-01",lastOpenedAt:null}},
  {persona:persona("2","Tomas Vale","fantasy"),metadata:{favorite:false,tags:["Cyberpunk"],archived:true,updatedAt:"2024-03-02",createdAt:"2024-01-02",lastOpenedAt:null}}
];
test("library index searches identity fields and tags without prose",()=>{assert.match(libraryIndex(records[0].persona,records[0].metadata),/vesper.*modern.*baker.*protagonist/);assert.doesNotMatch(libraryIndex(records[0].persona,records[0].metadata),/generated/);});
test("library query applies view, search, archive exclusion, and deterministic sorting",()=>{assert.deepEqual(queryLibrary(records,{query:"cyberpunk",view:"archived"}).map(item=>item.persona.meta.persona_id),["2"]);assert.deepEqual(queryLibrary(records,{view:"all",sort:"name"}).map(item=>item.persona.meta.persona_id),["1"]);assert.deepEqual(queryLibrary(records,{view:"favorites"}).map(item=>item.persona.meta.persona_id),["1"]);});
test("library query applies bounded canonical filters without mutating records",()=>{const before=JSON.stringify(records);assert.deepEqual(queryLibrary(records,{filters:{"foundation.setting":"modern"}}).map(item=>item.persona.meta.persona_id),["1"]);assert.equal(JSON.stringify(records),before);});
test("library query can filter normalized workspace tags",()=>{assert.deepEqual(queryLibrary(records,{view:"archived",filters:{tags:"cyberpunk"}}).map(item=>item.persona.meta.persona_id),["2"]);});
test("recent view orders by last opened when available and excludes archived records",()=>{const items=records.map(record=>({...record,metadata:{...record.metadata,lastOpenedAt:record.persona.meta.persona_id==="1"?"2024-05-01":"2024-04-01"}}));assert.deepEqual(queryLibrary(items,{view:"recent"}).map(item=>item.persona.meta.persona_id),["1"]);});
test("library query remains bounded across representative saved-library sizes",()=>{for(const size of [10,50,100,250,500]){const many=Array.from({length:size},(_,index)=>({persona:persona(String(index+1),`Character ${index+1}`),metadata:{favorite:index%7===0,tags:index%5===0?["protagonist"]:[],archived:index%11===0,updatedAt:`2024-03-${String((index%28)+1).padStart(2,"0")}`,createdAt:`2024-01-${String((index%28)+1).padStart(2,"0")}`,lastOpenedAt:null}}));const start=performance.now();for(let pass=0;pass<20;pass++){queryLibrary(many,{query:"character 4",view:"all",sort:"updated"});queryLibrary(many,{view:"favorites",sort:"name"});queryLibrary(many,{view:"archived",sort:"created"});}assert.ok(performance.now()-start<1000,`library query exceeded 1s at ${size} records`);}});
