import test from "node:test";
import assert from "node:assert/strict";
import { LocationStore } from "../src/location-store.js";
import { getLocationType } from "../src/location-types.js";
class Memory { constructor(){this.data=new Map();} getItem(k){return this.data.get(k)||null;} setItem(k,v){this.data.set(k,v);} }
test("locations are stable reference records with optional real and fictional geography",()=>{const store=new LocationStore(new Memory()); const parent=store.create({name:"Tokyo",type:"city",geography:{country:"Japan",city:"Tokyo"}}); const child=store.create({name:"Shibuya Apartment",type:"apartment",parentRef:{type:"location",id:parent.id},geography:{world:"Earth",city:"Tokyo",district:"Shibuya"}}); assert.equal(getLocationType("apartment").label,"Apartment"); assert.deepEqual(store.ancestry(child.id).map(x=>x.id),[parent.id,child.id]); const edited=store.update(child.id,{description:"Home"}); assert.equal(edited.id,child.id); assert.throws(()=>store.update(parent.id,{parentRef:{type:"location",id:child.id}}));});
test("missing parents remain diagnosable and deleting parents preserves children",()=>{const store=new LocationStore(new Memory()); const parent=store.create({name:"Parent",type:"region"}); const child=store.create({name:"Child",type:"town",parentRef:{type:"location",id:parent.id}}); store.delete(parent.id); const diagnostics=store.diagnostics([]); assert.deepEqual(diagnostics.missingParentRefs,[child.id]); assert.equal(store.open(child.id).id,child.id);});
test("collision-safe import remaps project and child parent references",()=>{const memory=new Memory(), store=new LocationStore(memory); store.create({id:"location_city",name:"Existing",type:"city"}); const result=store.importBrowserData({locations:[{id:"location_city",name:"Imported City",type:"city"},{id:"location_home",name:"Home",type:"apartment",parentRef:{type:"location",id:"location_city"}}],projects:[]},{projectMap:{}}); assert.equal(result.imported,2); const home=store.all().find(x=>x.name==="Home"); assert.equal(home.parentRef.id,result.idMap.location_city);});
test("cyclic imported evidence is retained for diagnostics rather than silently rewritten",()=>{const store=new LocationStore(new Memory()); const result=store.importBrowserData({locations:[{id:"location_a",name:"A",type:"region",parentRef:{type:"location",id:"location_b"}},{id:"location_b",name:"B",type:"region",parentRef:{type:"location",id:"location_a"}}]}); assert.equal(result.imported,2); assert.deepEqual(new Set(store.diagnostics([]).hierarchyCycles),new Set(["location_a","location_b"]));});
test("raw invalid proposed records are rejected before normalization",()=>{const store=new LocationStore(new Memory()); assert.throws(()=>store.create({name:"Bad",type:"not-a-type"})); const result=store.importBrowserData({locations:[{id:"location_bad",name:"Bad",type:"not-a-type"}]}); assert.equal(result.imported,0); assert.equal(store.diagnostics([]).unknownTypes.length,0);});
