import test from "node:test";
import assert from "node:assert/strict";
import { resolveMultiPersonProjection, multiPersonMarkdown } from "../src/multi-person-projection.js";
import { resolveSceneForge } from "../src/scene-forge.js";
import { normalizeScene } from "../src/scene-store.js";
const persona = (id, name, hair) => ({ meta: { persona_id: id }, origin: { name }, foundation: { species: { name: "human" }, life_stage: { name: "adult" } }, appearance: { visual: { hair, body: "average build", eyes: `${name} eyes` } }, life: {}, interests: {}, narrative: {} });
test("multi-person projection is deterministic and preserves identity separation", () => { const people = [persona("a", "Ari", "black hair"), persona("b", "Bea", "red hair")], scene = normalizeScene({ id: "s", seed: "fixed", participantRefs: [{ type: "persona", id: "a" }, { type: "persona", id: "b" }], focusPersonaRef: { type: "persona", id: "a" }, requirements: { action: "compare notes" } }); const before = structuredClone(people), one = resolveMultiPersonProjection({ scene, personas: people }), two = resolveMultiPersonProjection({ scene, personas: people }); assert.deepEqual(one, two); assert.equal(one.participants.find(p => p.id === "a").identity.hair, "black hair"); assert.equal(one.participants.find(p => p.id === "b").identity.hair, "red hair"); assert.deepEqual(people, before); assert.match(multiPersonMarkdown(one), /Visual prompt/); });
test("relationship evidence and cast expansion remain explicit", () => { const people = [persona("a", "Ari", "black"), persona("b", "Bea", "red")], scene = normalizeScene({ id: "s", seed: "x", participantRefs: [{ type: "persona", id: "a" }], focusPersonaRef: { type: "persona", id: "a" }, castRef: { type: "cast", id: "c" }, relationshipRefs: [{ type: "relationship", id: "r" }] }); const result = resolveSceneForge({ scene, personas: people, casts: [{ id: "c", personaRefs: [{ type: "persona", id: "b" }] }], relationships: [{ id: "r", type: "mentor", sourceRef: { id: "a" }, targetRef: { id: "b" } }], library: {} }); assert.equal(result.multiPersonProjection.status, "ready"); assert.equal(result.multiPersonProjection.participants.length, 2); assert.match(result.multiPersonProjection.prompt, /mentor/i); });
test("missing references degrade honestly", () => { const scene = normalizeScene({ id: "s", participantRefs: [{ type: "persona", id: "gone" }] }); const result = resolveMultiPersonProjection({ scene, personas: [] }); assert.equal(result.status, "empty"); assert.ok(result.warnings.length); });
