import test from "node:test";import assert from "node:assert/strict";import {PersonaStore,normalizeLibraryMetadata} from "../src/persona-store.js";
class MemoryStorage{constructor(){this.values=new Map()}getItem(key){return this.values.get(key)??null}setItem(key,value){this.values.set(key,value)}}
const persona=()=>({meta:{persona_id:"p1",seed:42,schema_version:"1.0",data_version:"0.1.0"},origin:{name:"Aiko Sato"},state:{locks:{"foundation.country":true},stale_fields:["life.housing"]}});
test("save and open preserve seed versions locks and state",()=>{const store=new PersonaStore(new MemoryStorage());store.save(persona());const opened=store.open("p1");assert.equal(opened.meta.seed,42);assert.equal(opened.meta.schema_version,"1.0");assert.deepEqual(opened.state.locks,{"foundation.country":true});assert.deepEqual(opened.state.stale_fields,["life.housing"]);});
test("save updates existing persona rather than duplicating",()=>{const store=new PersonaStore(new MemoryStorage());const first=persona();store.save(first);first.origin.name="Updated";store.save(first);assert.equal(store.all().length,1);assert.equal(store.open("p1").origin.name,"Updated");});
test("duplicate creates editable copy and delete removes only target",()=>{const store=new PersonaStore(new MemoryStorage());store.save(persona());const copy=store.duplicate("p1");assert.notEqual(copy.meta.persona_id,"p1");assert.equal(store.all().length,2);assert.ok(store.delete("p1"));assert.equal(store.all().length,1);assert.ok(store.open(copy.meta.persona_id));});
test("opening a legacy single value preserves it as primary only",()=>{const store=new PersonaStore(new MemoryStorage());const old=persona();old.personality={values:{id:"loyalty",name:"Loyalty"}};store.save(old);assert.deepEqual(store.open("p1").personality.values,{primary:old.personality.values,secondary:null,tension:null});});
test("workspace draft survives store reload and can be cleared",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.saveWorkspace(persona());const reopened=new PersonaStore(storage);assert.equal(reopened.workspace().meta.persona_id,"p1");reopened.clearWorkspace();assert.equal(reopened.workspace(),null);});
test("library metadata is separate, normalized, and survives reload",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);const source=persona();store.save(source);const before=JSON.stringify(store.open("p1"));const metadata=store.updateMetadata("p1",{favorite:true,tags:[" Cyberpunk ","cyberpunk","protagonist"],archived:true,variantLabel:"  Career Rewrite  "});assert.deepEqual(metadata.tags,["Cyberpunk","protagonist"]);assert.equal(metadata.favorite,true);assert.equal(metadata.archived,true);assert.equal(metadata.variantLabel,"Career Rewrite");assert.equal(JSON.stringify(store.open("p1")),before);const reopened=new PersonaStore(storage);assert.deepEqual(reopened.libraryMetadata("p1"),metadata);});
test("missing library metadata gets conservative defaults without historical dates",()=>{const metadata=normalizeLibraryMetadata({},"p1");assert.deepEqual(metadata,{favorite:false,tags:[],archived:false,createdAt:null,updatedAt:null,lastOpenedAt:null,variantLabel:"",lineage:null});});
test("duplicate copies tags but does not infer variant lineage",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());store.updateMetadata("p1",{tags:["protagonist"],lineage:null});const copy=store.duplicate("p1");assert.deepEqual(store.libraryMetadata(copy.meta.persona_id).tags,["protagonist"]);assert.equal(store.libraryMetadata(copy.meta.persona_id).lineage,null);});
test("variant creates an independent persona with explicit lineage",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());const variant=store.createVariant("p1","Career Rewrite");assert.notEqual(variant.meta.persona_id,"p1");assert.equal(store.libraryMetadata(variant.meta.persona_id).lineage.parentPersonaId,"p1");assert.equal(store.libraryMetadata(variant.meta.persona_id).variantLabel,"Career Rewrite");assert.equal(store.open("p1").origin.name,"Aiko Sato");});
test("library diagnostics report missing and invalid lineage without breaking records",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());store.updateMetadata("p1",{lineage:{parentPersonaId:"missing",relation:"variant"}});const report=store.libraryDiagnostics();assert.deepEqual(report.missingParents,[{id:"p1",parent:"missing"}]);assert.deepEqual(store.open("p1").origin.name,"Aiko Sato");});
test("browser data snapshot round-trips canonical records and separate metadata",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());store.updateMetadata("p1",{favorite:true,tags:["protagonist"]});const snapshot=store.browserData();assert.equal(snapshot.personas[0].meta.persona_id,"p1");assert.deepEqual(snapshot.personaLibrary.p1.tags,["protagonist"]);assert.equal(Object.hasOwn(snapshot.personas[0],"favorite"),false);const restored=new PersonaStore(new MemoryStorage());restored.write(snapshot.personas);restored.writeMetadata(snapshot.personaLibrary);assert.equal(restored.libraryMetadata("p1").favorite,true);});
test("deleting a variant parent leaves the child loadable with honest missing lineage",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());const variant=store.createVariant("p1","Career Rewrite");assert.equal(store.delete("p1"),true);assert.equal(store.open(variant.meta.persona_id).origin.name,"Aiko Sato Variant");assert.deepEqual(store.libraryDiagnostics().missingParents,[{id:variant.meta.persona_id,parent:"p1"}]);});
test("browser import preserves metadata, remaps imported lineage, and never overwrites collisions",()=>{const storage=new MemoryStorage();const store=new PersonaStore(storage);store.save(persona());const incoming=new PersonaStore(new MemoryStorage());incoming.save(persona());const variant=incoming.createVariant("p1","Imported Branch");const result=store.importBrowserData(incoming.browserData());assert.equal(result.imported,2);assert.equal(result.renamed.length,1);const importedId=variant.meta.persona_id;const importedMetadata=store.libraryMetadata(importedId);assert.equal(importedMetadata.variantLabel,"Imported Branch");assert.equal(importedMetadata.lineage.parentPersonaId,result.renamed.find(item=>item.from==="p1").to);assert.equal(store.all().length,3);assert.equal(store.open("p1").origin.name,"Aiko Sato");});
