import test from "node:test";
import assert from "node:assert/strict";
import { ProjectStore, PROJECT_SCHEMA_VERSION, normalizeProject, parseProjectImport, validateProject } from "../src/project-store.js";
import { ProjectCoordinator, attachProjectContext, markPersonaProjectReview, projectContextFor, projectGenerationOptions, resolveProjectInheritance, updatePersonaProjectOverride } from "../src/project-context.js";
import { PersonaStore } from "../src/persona-store.js";

class Memory { constructor(){this.map=new Map();} getItem(key){return this.map.get(key)??null;} setItem(key,value){this.map.set(key,value);} removeItem(key){this.map.delete(key);} }
const persona=(id="persona_a")=>({meta:{persona_id:id,seed:"seed",variance:"varied",schema_version:"2.0",data_version:"0.4.0"},foundation:{setting:{id:"modern"},era:{id:"contemporary"},country:{id:"country_united_kingdom"},species:{id:"human"}},origin:{name:"A"},personality:{},life:{},interests:{},appearance:{},state:{locks:{},stale_fields:[],warnings:[]}});

test("project creation has explicit versions, defaults, context, state, and future entity boundaries",()=>{const store=new ProjectStore(new Memory());const project=store.create({name:"Neon London",context:{setting:"cyberpunk",era:"2087",country:"country_united_kingdom"},versions:{data:"0.4.0",personaSchema:"2.0"}});assert.equal(project.schemaVersion,PROJECT_SCHEMA_VERSION);assert.equal(project.versions.application,"0.5.0");assert.equal(project.context.era,"2087");assert.deepEqual(Object.keys(project.entities),["casts","groups","relationships","locations","scenes"]);});

test("serialization is stable and import requires preview with collision-safe confirmation",()=>{const store=new ProjectStore(new Memory());const project=store.create({name:"Portable"});const one=store.export(project.id),two=store.export(project.id);assert.equal(one,two);const preview=parseProjectImport(one);assert.equal(preview.valid,true);const imported=store.confirmImport(preview);assert.equal(imported.collision,true);assert.notEqual(imported.project.id,project.id);assert.throws(()=>store.confirmImport({valid:false}));});
test("portable project export and duplication intentionally omit relationship refs",()=>{const store=new ProjectStore(new Memory()), project=store.create({name:"Graph",relationshipRefs:[{type:"relationship",id:"r1"}]}); assert.deepEqual(JSON.parse(store.export(project.id)).project.relationshipRefs,[]); const copy=store.duplicate(project.id); assert.deepEqual(copy.relationshipRefs,[]);});

test("malformed and future project schemas are rejected honestly",()=>{assert.equal(validateProject({}).valid,false);assert.match(validateProject({id:"x",name:"Future",schemaVersion:99}).issues.join(" "),/newer/);assert.equal(parseProjectImport("not json").valid,false);});

test("inheritance distinguishes project, explicit override, and independent values",()=>{const project=normalizeProject({id:"p",name:"P",context:{setting:"cyberpunk",era:"2087",country:"gb"}});const result=resolveProjectInheritance(project,{country:"jp"});assert.equal(result.sources.setting.source,"project");assert.equal(result.sources.country.source,"persona");assert.equal(result.sources.country.overridden,true);assert.equal(result.sources.species.source,"independent");});

test("persona project provenance records inheritance and explicit overrides",()=>{const project=normalizeProject({id:"p",name:"P",context:{setting:"cyberpunk",country:"gb"}});let saved=attachProjectContext(persona(),project,{country:"jp"});let link=projectContextFor(saved,"p");assert.equal(link.inherited.setting,"cyberpunk");assert.equal(link.overrides.country,"jp");saved=updatePersonaProjectOverride(saved,project,"country","fr");link=projectContextFor(saved,"p");assert.equal(link.sources.country.source,"persona");assert.equal(link.sources.country.projectValue,"gb");});

test("project changes mark only inheriting context for review and never rewrite canonical persona",()=>{const project=normalizeProject({id:"p",name:"P",context:{setting:"cyberpunk",era:"2087",country:"gb"}});const linked=attachProjectContext(persona(),project,{country:"jp"});const before=structuredClone(linked.foundation);const marked=markPersonaProjectReview(linked,project,["era","country"]);assert.deepEqual(marked.foundation,before);assert.deepEqual(projectContextFor(marked,"p").review.changedContext,["era"]);assert.ok(projectContextFor(marked,"p").review.affectedFields.includes("foundation.era"));});

test("coordinator membership is reference-only, multi-project capable, and removal/deletion preserve personas",()=>{const memory=new Memory(),personas=new PersonaStore(memory),projects=new ProjectStore(memory),coordinator=new ProjectCoordinator(projects,personas);personas.save(persona());const a=projects.create({name:"A"}),b=projects.create({name:"B"});coordinator.addPersona(a.id,"persona_a");coordinator.addPersona(b.id,"persona_a");assert.equal(projects.open(a.id).personaRefs.length,1);coordinator.removePersona(a.id,"persona_a");assert.ok(personas.open("persona_a"));assert.equal(projectContextFor(personas.open("persona_a"),a.id),null);coordinator.deleteProject(b.id);assert.ok(personas.open("persona_a"));assert.equal(projectContextFor(personas.open("persona_a"),b.id),null);});

test("project duplication gets a new identity without duplicating canonical personas",()=>{const memory=new Memory(),personas=new PersonaStore(memory),projects=new ProjectStore(memory),coordinator=new ProjectCoordinator(projects,personas);personas.save(persona());const created=projects.create({name:"Source"});coordinator.addPersona(created.id,"persona_a");const source=projects.open(created.id),copy=coordinator.duplicateProject(source.id);assert.notEqual(copy.id,source.id);assert.deepEqual(copy.personaRefs,source.personaRefs);assert.equal(personas.all().length,1);assert.ok(projectContextFor(personas.open("persona_a"),copy.id));});

test("context changes persist review state while preserving explicit country override",()=>{const memory=new Memory(),personas=new PersonaStore(memory),projects=new ProjectStore(memory),coordinator=new ProjectCoordinator(projects,personas);const project=projects.create({name:"Neon London",context:{setting:"cyberpunk",era:"2087",country:"gb"}});personas.save(attachProjectContext(persona(),project,{country:"jp"}));projects.addPersona(project.id,"persona_a");coordinator.updateContext(project.id,{...project.context,era:"2094"});assert.equal(projects.open(project.id).memberState.persona_a.needsReview,true);const saved=personas.open("persona_a");assert.equal(projectContextFor(saved,project.id).overrides.country,"jp");assert.equal(saved.foundation.country.id,"country_united_kingdom");});

test("project generation inputs are deterministic, explicit anchors win, and unknown contextual labels stay provenance-only",()=>{const project=normalizeProject({id:"p",name:"P",context:{setting:"cyberpunk",era:"2087",country:"gb"},defaults:{varianceMode:"grounded"}});const library={settings:[{id:"cyberpunk"}],eras:[{id:"future"}],countries:[{id:"gb"}],species:[]};const a=projectGenerationOptions(project,{seed:"same",anchors:{country:"jp"},library}),b=projectGenerationOptions(project,{seed:"same",anchors:{country:"jp"},library});assert.deepEqual(a,b);assert.deepEqual(a.anchors,{setting:"cyberpunk"});assert.equal(a.projectInheritance.sources.country.source,"persona");assert.equal(a.projectInheritance.effective.era,"2087");});

test("standalone personas normalize without a forced project",()=>{const store=new PersonaStore(new Memory());store.save(persona("standalone"));assert.deepEqual(store.open("standalone").extensions.promptforge.projectContexts,{});});

test("project variance uses the canonical chaotic term and normalizes legacy wild input",()=>{const canonical=normalizeProject({id:"canonical",name:"Canonical",defaults:{varianceMode:"chaotic"}});const legacy=normalizeProject({id:"legacy",name:"Legacy",defaults:{varianceMode:"wild"}});assert.equal(canonical.defaults.varianceMode,"chaotic");assert.equal(legacy.defaults.varianceMode,"chaotic");});
