import test from "node:test";
import assert from "node:assert/strict";
import { ProjectStore, normalizeProject } from "../src/project-store.js";
class Memory { constructor(){this.map=new Map();} getItem(k){return this.map.get(k)??null;} setItem(k,v){this.map.set(k,v);} removeItem(k){this.map.delete(k);} }
const persona = id => ({ meta: { persona_id: id } });
test("projects store references, not persona copies", () => { const store = new ProjectStore(new Memory()); const project = store.create({name:"Neon Tokyo", context:{setting:"Futuristic", era:"2043"}}); store.addPersona(project.id,"persona_a"); assert.deepEqual(store.open(project.id).personaRefs,[{type:"persona",id:"persona_a"}]); assert.equal(store.open(project.id).personas,undefined); });
test("missing references are honest and removable", () => { const store = new ProjectStore(new Memory()); const project = store.create({name:"Test"}); store.addPersona(project.id,"gone"); assert.equal(store.diagnostics([persona("other")]).missingReferences,1); store.removePersona(project.id,"gone"); assert.equal(store.open(project.id).personaRefs.length,0); });
test("resolved references are counted correctly", () => { const store = new ProjectStore(new Memory()); const project = store.create({name:"Test"}); store.addPersona(project.id,"present"); assert.equal(store.diagnostics([persona("present")]).resolvedReferences,1); });
test("malformed references remain inspectable as invalid", () => { const store = new ProjectStore(new Memory()); store.write([normalizeProject({id:"project_invalid",name:"Invalid",personaRefs:[{type:"persona"},{type:"future",id:"x"} ]})]); assert.equal(store.diagnostics([]).invalidReferences,2); });
test("duplicate membership is prevented and project deletion preserves personas", () => { const store = new ProjectStore(new Memory()); const project = store.create({name:"Test"}); store.addPersona(project.id,"p"); store.addPersona(project.id,"p"); assert.equal(store.open(project.id).personaRefs.length,1); assert.equal(store.delete(project.id),true); });
test("normalization and collision-safe import preserve project references", () => { const store = new ProjectStore(new Memory()); store.write([normalizeProject({id:"project_x",name:"Local"})]); const result = store.importBrowserData({projects:[{id:"project_x",name:"Imported",personaRefs:[{type:"persona",id:"missing"}]}]}); assert.equal(result.renamed.length,1); assert.equal(store.all().length,2); assert.equal(store.all().find(p=>p.name==="Imported").personaRefs[0].id,"missing"); assert.equal(normalizeProject({schemaVersion:1}).schemaVersion,2); });
test("project v2 adds scene references and contextual extension points without embedding records", () => { const store=new ProjectStore(new Memory()); const project=store.create({name:"Everyday Life",locations:["Flat","Café"],notes:"Keep scenes grounded"}); store.addScene(project.id,"scene_a"); store.addScene(project.id,"scene_a"); const saved=store.open(project.id); assert.deepEqual(saved.sceneRefs,[{type:"scene",id:"scene_a"}]); assert.deepEqual(saved.locations,["Flat","Café"]); assert.equal(saved.notes,"Keep scenes grounded"); assert.equal(saved.scenes,undefined); });
test("persona collision remaps imported project references", () => { const store = new ProjectStore(new Memory()); const result = store.importBrowserData({projects:[{id:"project_import",name:"Imported",personaRefs:[{type:"persona",id:"persona_old"}]}]}, new Set(["persona_new"]), {personaMap:{persona_old:"persona_new"}}); assert.equal(result.imported,1); assert.equal(store.all()[0].personaRefs[0].id,"persona_new"); });
