import { loadLibrary } from "./data-loader.js";
import { generatePersona } from "./generator.js";
import { PersonaController } from "./persona-controller.js";
import { writePersona, personaText } from "./persona-writer.js";
import { referencePackage, referenceMarkdown } from "./reference-writer.js";
import { PersonaStore } from "./persona-store.js";

const state = { library: null, persona: null, controller: null };
const store = new PersonaStore();
const form = document.querySelector("#foundation-form"); const cards = document.querySelector("#cards"); const status = document.querySelector("#status");
const label = (value) => value?.name ?? value ?? "—";
function populate(name, entries) { form.elements[name].innerHTML = `<option value="">Random</option>${entries.map((entry) => `<option value="${entry.id}">${entry.name}</option>`).join("")}`; }
function display(value) { if (Array.isArray(value)) return value.map(label).join(", "); if (value && typeof value === "object" && !value.name) return Object.values(value).map(label).join(", "); return label(value); }
function rows(section, values) { const entries=section==="personality"?Object.entries(values).flatMap(([key,value])=>key==="values"?Object.entries(value).map(([role,item])=>[`values.${role}`,item]):[[key,value]]):Object.entries(values); return entries.filter(([key,value])=>key!=="integration"&&(!key.endsWith(".tension")||value)).map(([key,value]) => { const path=`${section}.${key}`; const locked=state.persona.state.locks[path]; const stale=state.persona.state.stale_fields.includes(path); const title={"values.primary":"Primary Value","values.secondary":"Secondary Value","values.tension":"Value Tension"}[key]||key.replaceAll("_"," "); return `<div class="field"><span class="${stale?"stale":""}">${title}${stale?" ⚠":""}</span><span>${display(value)}</span><span class="field-actions"><button class="icon-button ${locked?"locked":""}" data-action="lock" data-path="${path}">${locked?"Locked":"Lock"}</button><button class="icon-button" data-action="reroll" data-path="${path}" ${locked?"disabled":""}>Reroll</button></span></div>`; }).join(""); }
function narrativePanel(integration) { if(!integration)return ""; const entries=[...["motivation",integration.motivations?.[0]], ["short-term goal",integration.goals?.short_term], ["long-term goal",integration.goals?.long_term], ["internal tension",integration.tensions?.[0]], ["external pressure",integration.pressures?.[0]], ["relationship hook",integration.relationship_hooks?.[0]], ["arc seed",integration.arc_seeds?.[0]], ["scene hook",integration.scene_hooks?.[0]]].filter(([,item])=>item); return `<section class="narrative-panel"><div class="panel-heading horizontal"><div><p class="eyebrow">Derived narrative</p><h3>Current story state</h3></div><span class="muted">${integration.intensity||"ordinary"} intensity</span></div><div class="narrative-summary"><strong>${integration.goals?.short_term?.text||""}</strong><span>${integration.tensions?.[0]?.text||""}</span></div>${entries.map(([title,item])=>{const path=title==="motivation"?"narrative.integration.motivations.0":title==="short-term goal"?"narrative.integration.goals.short_term":title==="long-term goal"?"narrative.integration.goals.long_term":title==="internal tension"?"narrative.integration.tensions.0":title==="external pressure"?"narrative.integration.pressures.0":title==="relationship hook"?"narrative.integration.relationship_hooks.0":title==="arc seed"?"narrative.integration.arc_seeds.0":"narrative.integration.scene_hooks.0";const locked=state.persona.state.locks[path],stale=state.persona.state.stale_fields.includes(path);return `<details class="narrative-row"><summary><span class="${stale?"stale":""}">${title}${stale?" ⚠":""}</span><span>${item.text}</span></summary><div class="narrative-meta"><small>Domain: ${item.domain||"—"} · Sources: ${(item.sources||[]).join(", ")||"none"}</small><span class="field-actions"><button class="icon-button ${locked?"locked":""}" data-action="lock" data-path="${path}">${locked?"Locked":"Lock"}</button><button class="icon-button" data-action="reroll" data-path="${path}" ${locked?"disabled":""}>Reroll</button></span></div></details>`;}).join("")}</section>`; }
function card(section,title,values,open=false) { return `<details class="persona-card" ${open?"open":""}><summary><span>${title}</span><span class="card-actions"><button class="icon-button" data-action="lock-section" data-section="${section}">Lock card</button><button class="icon-button" data-action="reroll-section" data-section="${section}">Reroll card</button></span></summary><div class="card-body">${rows(section,values)}</div></details>`; }
function render() {
  const p=state.persona; document.querySelector("#persona-name").textContent=p.origin.name;
  document.querySelector("#narrative-panel").innerHTML=narrativePanel(p.narrative.integration);
  cards.innerHTML=[card("foundation","Foundation",p.foundation,true),card("origin","Origin",p.origin),card("personality","Personality",p.personality),card("life","Life",p.life),card("interests","Interests",p.interests),card("appearance","Appearance",{surface:p.appearance.surface,clothing_style:p.appearance.clothing_style,signature_outfit:p.appearance.signature_outfit}),card("narrative","Narrative",p.narrative,true),card("character_hook","Character Hook",{text:p.character_hook.text},true)].join("");
  const locks=Object.keys(p.state.locks), stale=p.state.stale_fields, warnings=p.state.warnings;
  const checks=(p.state.coherence_checks||[]).map((check)=>`${check.status==="pass"?"✓":"⚠"} ${check.name}`).join("<br>");
  document.querySelector("#context").innerHTML=`<div class="context-block"><h3>Seed</h3><p>${p.meta.seed}</p></div><div class="context-block"><h3>Locks</h3><p>${locks.length?locks.join(", "):"None — fully random"}</p></div><div class="context-block"><h3>Dependencies</h3><p class="${stale.length?"stale":""}">${stale.length?`${stale.length} field(s) may no longer align.`:"No stale fields."}</p>${stale.length?'<p class="card-actions"><button data-action="regenerate-affected">Regenerate affected</button><button data-action="keep-existing">Keep existing</button></p>':""}</div><div class="context-block"><h3>Character Hook</h3><p><button data-action="reroll-hook">New Direction</button></p></div><div class="context-block"><h3>Data contract</h3><p>Schema ${p.meta.schema_version} · Data ${p.meta.data_version}</p></div><div class="context-block"><h3>Coherence</h3><p class="${warnings.length?"warning":""}">${checks||"All deterministic checks passed."}</p></div>`;
  status.textContent="Generated";
  document.querySelector("#persona-output").textContent=writePersona(p);
  renderReference();
}
function renderReference(){if(!state.persona)return;const mode=document.querySelector("#prompt-mode").value;const prompts=referencePackage(state.persona,mode);const select=document.querySelector("#prompt-type");const selected=select.value;if(!select.options.length)select.innerHTML=Object.keys(prompts).map((key)=>`<option value="${key}">${key.replaceAll("_"," ")}</option>`).join("");if(selected&&prompts[selected])select.value=selected;document.querySelector("#reference-output").textContent=prompts[select.value||"master"];}
function escapeHtml(value){return String(value).replace(/[&<>"]/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[character]));}
function renderLibrary(){const items=store.all();document.querySelector("#library-list").innerHTML=items.length?items.map((p)=>`<div class="library-row"><div><strong>${escapeHtml(p.origin.name)}</strong><br><small>Seed ${escapeHtml(p.meta.seed)} · Schema ${escapeHtml(p.meta.schema_version)} · Data ${escapeHtml(p.meta.data_version)}</small></div><span class="field-actions"><button data-library-action="open" data-id="${escapeHtml(p.meta.persona_id)}">Open</button><button data-library-action="duplicate" data-id="${escapeHtml(p.meta.persona_id)}">Duplicate</button><button data-library-action="export" data-id="${escapeHtml(p.meta.persona_id)}">JSON</button><button data-library-action="delete" data-id="${escapeHtml(p.meta.persona_id)}">Delete</button></span></div>`).join(""):'<div class="empty-state">No saved personas yet.</div>';}
function anchorsFromForm(){const values=Object.fromEntries(new FormData(form));const anchors=Object.fromEntries(Object.entries(values).filter(([,value])=>value!==""));if(anchors.age)anchors.age=Number(anchors.age);return anchors;}
document.querySelector("#generate").addEventListener("click",()=>{try{state.persona=generatePersona(state.library,{seed:document.querySelector("#seed").value||Date.now(),mode:document.querySelector("#variance").value,anchors:anchorsFromForm()});state.controller=new PersonaController(state.library,state.persona);render();}catch(error){status.textContent="Generation failed";document.querySelector("#context").innerHTML=`<p class="warning">${error.message}</p>`;}});
document.addEventListener("click",(event)=>{const button=event.target.closest("button[data-action]");if(!button||!state.controller)return;event.preventDefault();event.stopPropagation();const action=button.dataset.action;if(action==="lock")state.controller.toggleLock(button.dataset.path);if(action==="reroll")state.controller.rerollField(button.dataset.path);if(action==="lock-section")state.controller.toggleSection(button.dataset.section);if(action==="reroll-section")state.controller.rerollSection(button.dataset.section);if(action==="regenerate-affected")state.controller.regenerateAffected();if(action==="keep-existing")state.controller.keepExisting();if(action==="reroll-hook")state.controller.rerollHook();render();});
document.querySelector("#reroll-unlocked").addEventListener("click",()=>{if(state.controller){state.controller.rerollUnlocked();render();}});
document.querySelector(".tabs").addEventListener("click",(event)=>{const button=event.target.closest("button[data-tab]");if(!button)return;for(const item of document.querySelectorAll(".tabs button"))item.classList.toggle("active",item===button);for(const view of document.querySelectorAll(".tab-view"))view.hidden=view.id!==`${button.dataset.tab}-view`;});
function download(filename,text,type="text/plain"){const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([text],{type}));link.download=filename;link.click();URL.revokeObjectURL(link.href);}
document.querySelector("#copy-persona").addEventListener("click",async()=>{if(state.persona)await navigator.clipboard.writeText(writePersona(state.persona));});
document.querySelector("#export-persona-md").addEventListener("click",()=>{if(state.persona)download(`${state.persona.meta.persona_id}.md`,writePersona(state.persona),"text/markdown");});
document.querySelector("#export-persona-txt").addEventListener("click",()=>{if(state.persona)download(`${state.persona.meta.persona_id}.txt`,personaText(state.persona));});
document.querySelector("#prompt-mode").addEventListener("change",renderReference);document.querySelector("#prompt-type").addEventListener("change",renderReference);
document.querySelector("#reroll-visual").addEventListener("click",()=>{if(state.controller){state.controller.rerollVisual();render();}});
document.querySelector("#copy-prompt").addEventListener("click",async()=>{if(state.persona)await navigator.clipboard.writeText(document.querySelector("#reference-output").textContent);});
document.querySelector("#export-reference-md").addEventListener("click",()=>{if(state.persona)download(`${state.persona.meta.persona_id}_reference.md`,referenceMarkdown(state.persona,document.querySelector("#prompt-mode").value),"text/markdown");});
document.querySelector("#save-persona").addEventListener("click",()=>{if(state.persona){state.persona=store.save(state.persona);state.controller=new PersonaController(state.library,state.persona);render();renderLibrary();status.textContent="Saved";}});
document.querySelector("#library-list").addEventListener("click",(event)=>{const button=event.target.closest("button[data-library-action]");if(!button)return;const id=button.dataset.id,action=button.dataset.libraryAction;if(action==="open"){state.persona=store.open(id);state.controller=new PersonaController(state.library,state.persona);render();}if(action==="duplicate"){state.persona=store.duplicate(id);state.controller=new PersonaController(state.library,state.persona);render();}if(action==="export"){const persona=store.open(id);download(`${id}.json`,JSON.stringify(persona,null,2),"application/json");}if(action==="delete")store.delete(id);renderLibrary();});
try{state.library=await loadLibrary("./data");populate("setting",state.library.settings);populate("era",state.library.eras);populate("species",state.library.species);populate("life_stage",state.library.lifeStages);populate("country",state.library.countries);renderLibrary();status.textContent="Ready";}catch(error){status.textContent="Data error";document.querySelector("#context").innerHTML=`<p class="warning">Run PersonaForge through a local web server. ${error.message}</p>`;}
