import { escapeHtml as e, greeting, coverageLabel } from "./hub-store.js";
export const pages = { overview:"Overview", forge:"My Forge", editor:"Pool editor", profile:"Profile", preferences:"Preferences", appearance:"Appearance", presets:"Presets", activity:"Activity", backup:"Data & Backup", diagnostics:"Diagnostics", about:"About" };
const button = (action, text, extra = "") => `<button data-hub-action="${action}" ${extra}>${text}</button>`;
const route = (page, text) => `<a class="hub-link" href="#hub/${page}">${text} <span aria-hidden="true">↗</span></a>`;
const date = value => value ? new Date(value).toLocaleString() : "Not yet recorded";
const empty = text => `<p class="hub-empty">${text}</p>`;
export const card = (title, body, className = "", eyebrow = "") => `<section class="hub-card ${className}">${eyebrow ? `<p class="eyebrow">${eyebrow}</p>` : ""}<h3>${title}</h3>${body}</section>`;
export function healthSummary(audit) {
  return audit ? `<div class="hub-metrics">${["errors", "warnings", "info"].map(key => `<div><strong>${e(audit.summary[key])}</strong><span>${key}</span></div>`).join("")}</div><p class="muted">${audit.summary.errors ? "Errors need attention" : audit.summary.warnings ? "Review warnings" : "No errors or warnings"} · ${e(date(audit.at))}</p>` : empty("Not audited yet. Run a health audit to check schema, coverage, and similarity.");
}
export function poolCard(pool) {
  const key = `${pool.kind}:${pool.branch}`;
  return `<a class="hub-pool" href="#hub/forge/${encodeURIComponent(key)}"><div class="hub-row"><strong>${e(pool.branch.replaceAll("_", " "))}</strong><span class="hub-badge" data-status="${e(pool.status)}">${e(coverageLabel(pool.status))}</span></div><div class="hub-row muted"><span>${e(pool.kind)}${pool.ignored || pool.priority === "ignored" ? " · ignored in recommendations" : ""}</span><strong>${pool.current.toLocaleString()} entries</strong></div><progress max="${Math.max(1,pool.target)}" value="${Math.min(pool.current,pool.target)}" aria-label="${e(pool.branch)} target coverage"></progress><div class="hub-thresholds"><span>Minimum <b>${pool.minimum}</b><small>Gap ${pool.needed_to_minimum}</small></span><span>Healthy <b>${pool.healthy}</b><small>Gap ${pool.needed_to_healthy}</small></span><span>Target <b>${pool.target}</b><small>Gap ${pool.needed_to_target}</small></span></div></a>`;
}
export function timeline(items) {
  return items.length ? `<ol class="hub-timeline">${items.map(item => `<li><span class="hub-dot" aria-hidden="true"></span><div><strong>${e(item.title)}</strong><small>${e(item.type)} · ${e(date(item.at))}${item.observation ? " · observed on refresh" : ""}</small>${item.branch ? route(`forge/${encodeURIComponent(item.branch)}`, "Inspect pool") : ""}</div></li>`).join("")}</ol>` : empty("No activity yet. Meaningful work will appear here as you use the Forge.");
}
function presetList(presets) {
  return presets.length ? presets.map(p => `<article class="hub-preset"><div class="hub-row"><div><small class="eyebrow">Generation preset</small><h3>${e(p.name)}</h3></div>${button("favorite", p.favorite ? "★ Favourite" : "☆ Favourite", `data-id="${e(p.id)}" aria-pressed="${!!p.favorite}"`)}</div><p class="muted">${e([p.mode,...(p.tags || []),...(p.lastUsed ? [`Used ${date(p.lastUsed)}`] : [])].filter(Boolean).join(" · "))}</p><div class="hub-actions">${["open","use","rename","tags","duplicate","delete"].map(a => button(`preset-${a}`, a[0].toUpperCase() + a.slice(1), `data-id="${e(p.id)}"`)).join("")}</div></article>`).join("") : empty("Save your current studio controls as a preset to reuse a generation setup.");
}
const select = (name, label, values, current) => `<label>${label}<select name="${name}">${values.map(v => { const [value, title] = Array.isArray(v) ? v : [v,v]; return `<option value="${e(value)}" ${current === value ? "selected" : ""}>${e(title)}</option>`; }).join("")}</select></label>`;
const check = (name, label, value) => `<label class="hub-check"><input type="checkbox" name="${name}" ${value ? "checked" : ""}>${label}</label>`;
export function renderPage(page, ctx) {
  const { model:m, data:d, activity, query, filter, selected, settings } = ctx;
  const pools = d?.pools || [];
  const toolbar = `<div class="hub-toolbar"><label>Find a pool<input id="hub-search" value="${e(query)}" placeholder="Search names or branches"></label><label>Coverage filter<select id="hub-filter">${[["all","All statuses"],["deficient","Below minimum"],["minimum","Minimum met"],["healthy","Healthy but below target"],["target_met","Target reached"],["saturated","Saturated"],["Complete","Complete"]].map(([v,t]) => `<option value="${v}" ${filter === v ? "selected" : ""}>${t}</option>`).join("")}</select></label></div>`;
  if (page === "overview") {
    const attention = pools.filter(p => !p.ignored && p.priority !== "ignored" && p.status === "deficient").sort((a,b) => b.needed_to_minimum-a.needed_to_minimum);
    const relevant = attention.length ? attention.slice(0,3) : pools.filter(p => p.status === "healthy").slice(0,3);
    return `<div class="hub-grid">${card(e(greeting(m.profile.name)), `<p class="hub-lead">Your ideas. Your tools. Your Forge.</p>${m.profile.tagline ? `<p class="muted">${e(m.profile.tagline)}</p>` : ""}<div class="hub-actions">${route("studio", "Open studio")}${button("continue", "Continue working")}</div><p class="muted">${m.lastWork ? `Last workspace: ${e(m.lastWork.title)}` : "A fresh workspace is ready when you are."}</p>`, "hub-welcome hub-wide", "CONTROL CENTRE")}${card("Forge health", (d ? healthSummary(d.audit) : empty("Audit data is not connected yet.")) + route("diagnostics", "View diagnostics"))}${card("At a glance", d ? `<div class="hub-metrics"><div><strong>${d.entries.toLocaleString()}</strong><span>Entries</span></div><div><strong>${d.catalogues}</strong><span>Catalogues</span></div><div><strong>${d.deep_pools}</strong><span>Deep pools</span></div></div><p class="muted">${d.templates} entry templates · ${m.presets.length} personal presets</p>` : empty("Connect the local server to see live catalogue totals."), "hub-wide")}${card("Quick actions", `<div class="hub-actions">${button("generate", "Generate")}${button("audit", "Run audit")}${button("backup", "Backup now")}${route("forge", "Inspect pools")}</div>`)}${card(attention.length ? "Needs some love" : "Keep creating", relevant.length ? relevant.map(poolCard).join("") : empty(d ? "No under-target pools to highlight." : "Coverage will appear when the local server connects."), "hub-wide")}${activity.some(i => i.type === "pools" && i.delta > 0) ? card("Recently expanded", timeline(activity.filter(i => i.type === "pools" && i.delta > 0).slice(0,3)), "hub-full") : ""}${card("Recent activity", timeline(activity.slice(0,5)) + route("activity", "All activity"))}${card("Personal presets", presetList([...m.presets].sort((a,b) => Number(b.favorite)-Number(a.favorite) || (b.lastUsed || "").localeCompare(a.lastUsed || "")).slice(0,2)) + route("presets", "Manage presets"), "hub-wide")}${card("This session", `<div class="hub-metrics">${[["generation","Generation actions"],["presets","Preset actions"],["diagnostics","Audits"]].map(([type,title]) => `<div><strong>${ctx.session.filter(i => i.type === type).length}</strong><span>${title}</span></div>`).join("")}</div><p class="muted">Since this page was opened.</p>`)}${card("Safe & current", `<p class="muted">Last catalogue backup: ${e(date(d?.backups?.[0]?.at))}</p><p class="muted">Application ${e(d?.versions.application_version || "unavailable")} · Data ${e(d?.versions.data_version || "unavailable")}</p>${route("backup", "Data & Backup")}`, "hub-full")}</div>`;
  }
  if (page === "forge") {
    const pool = pools.find(p => `${p.kind}:${p.branch}` === selected);
    const selectedCategory = selected && !pool ? selected.split(":").slice(1).join(":") : "";
    const matches = pools.filter(p => (!selectedCategory || p.branch === selectedCategory || p.branch.startsWith(selectedCategory + "/")) && p.branch.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || p.status === filter));
    const categories = [...new Set(pools.map(p => p.branch.split("/")[0]))];
    const systems = `<div class="hub-systems">${categories.map(category => { const rows = pools.filter(p => p.branch.split("/")[0] === category && !p.ignored && p.priority !== "ignored"); return `<button data-hub-category="${e(category)}"><strong>${e(category)}</strong><small>${rows.filter(p => p.status === "deficient").length} below minimum · ${rows.filter(p => ["target_met","saturated","Complete"].includes(p.status)).length} at target</small></button>`; }).join("")}</div>`;
    return `<p class="hub-lead">Coverage with context. Every threshold stays visible.</p>${systems}${selected ? pool ? card(e(pool.branch), poolCard(pool) + `<p class="muted">${pool.kind === "deep" ? "Registry leaf pool. Counts use metadata.pool_id." : "Catalogue pool. Subcategories overlap their parent totals."}</p><p>Inspect with the Populator CLI:</p><code>python populate.py ${pool.kind === "deep" ? "pool-inspect" : "browse"} ${e(pool.id || pool.category)}</code>${pool.category ? `<p><a href="/data/${e(pool.category)}.json" target="_blank" rel="noopener">Open catalogue JSON ↗</a></p>` : ""}`) : empty("Choose an affected pool below. If none appear, this branch may have been removed.") : ""}${toolbar}<p class="muted">${matches.length} pools · Catalogue and deep-pool counts overlap; they are not additive.</p><div class="hub-pool-grid">${matches.length ? matches.map(poolCard).join("") : empty("No matching pools.")}</div>`;
  }
  if (page === "editor") return card("Review catalogue entries", `<p class="hub-lead">Paste an entry array, preview validation and duplicate findings, then apply only after review.</p><form data-hub-form="pool-editor"><label>Catalogue path<input name="category" required placeholder="personality/values"></label><label>Entries as JSON<textarea name="entries" rows="14" required placeholder='[{"id":"example","name":"Example","compatibility":{"settings":[],"eras":[],"species":[],"life_stages":[],"countries":[]}}]'></textarea></label><div class="hub-actions"><button class="primary" data-hub-action="pool-preview">Preview import</button><button data-hub-action="pool-apply" disabled>Apply reviewed entries</button></div></form><div id="pool-review" class="hub-review">No preview yet. Applying is disabled until the server validates this exact destination and payload.</div>`, "hub-form-card");
  if (page === "profile") return card("Make yourself at home", `<form data-hub-form="profile"><div class="hub-avatar" aria-hidden="true">${e(m.profile.avatar || m.profile.name.slice(0,2).toUpperCase() || "PF")}</div><label>Display name<input name="name" maxlength="60" value="${e(m.profile.name)}" autocomplete="nickname"></label><label>Avatar initials or emoji<input name="avatar" maxlength="8" value="${e(m.profile.avatar)}"></label><label>Creator label<input name="tagline" maxlength="140" value="${e(m.profile.tagline)}" placeholder="Writer, world-builder, curious human…"></label><p class="muted">Stored only in this browser. No account or sign-in required.</p><button class="primary">Save profile</button></form>`, "hub-form-card");
  if (page === "preferences") return card("Generation defaults", `<form data-hub-form="preferences">${select("mode","Default variance",["grounded","varied","chaotic"],m.preferences.mode)}${select("setting","Default setting",[["","Random"],...settings.map(s => [s.id,s.name])],m.preferences.setting)}${select("output","Reference output",["structured","polished"],m.preferences.output)}${check("autoCopy","Copy reference prompt after generation",m.preferences.autoCopy)}<p class="muted">Defaults apply on the next page load. Presets can override them. Clipboard access requires browser permission.</p><button class="primary">Save preferences</button></form>`, "hub-form-card");
  if (page === "appearance") return card("A space that feels like yours", `<form data-hub-form="appearance">${select("theme","Appearance",["dark","light","system"],m.appearance.theme)}${select("accent","Accent",["violet","indigo","teal"],m.appearance.accent)}${select("density","UI density",["comfortable","compact"],m.appearance.density)}${select("background","Workspace background",[["none","None"],["gradient","Subtle gradient"]],m.appearance.background)}${check("reducedMotion","Reduce motion",m.appearance.reducedMotion)}<p class="muted">Your system’s reduced-motion preference is always respected.</p><button class="primary">Save appearance</button></form>`, "hub-form-card");
  if (page === "presets") return `<p class="hub-lead">Keep the setups you come back to.</p><div class="hub-toolbar"><label>Search names and tags<input id="hub-search" value="${e(query)}" placeholder="Find a preset"></label>${button("save-preset","Save current studio setup",'class="primary"')}</div><div class="hub-pool-grid">${presetList(m.presets.filter(p => `${p.name} ${(p.tags || []).join(" ")}`.toLowerCase().includes(query.toLowerCase())))}</div><p class="muted">Generation presets store anchors, variance, and reference format. Saved personas remain in the Studio Library.</p>`;
  if (page === "activity") return `${select("activity-filter","Filter activity",["all","pools","generation","diagnostics","presets","backups","settings"],filter).replace('name="activity-filter"','id="hub-filter"')}${card("Your Forge, in motion", timeline(activity.filter(i => filter === "all" || i.type === filter)))}${d?.operations?.length ? card("Populator operation history", `<p class="muted">Existing CLI records have no timestamps, so they are shown separately.</p><ul>${[...d.operations].reverse().map(o => `<li>${e(o.action)} · ${o.files.length} files</li>`).join("")}</ul>`) : ""}`;
  if (page === "backup") return `<div class="hub-grid">${card("Catalogue backups", `<p class="muted">Data path: ${e(d?.data_path || "Unavailable")}</p><p>ZIP archives contain the data directory. Profile, browser presets, and saved personas are separate.</p><div class="hub-actions">${button("backup","Create backup",'class="primary"')}</div>${d?.backups?.length ? `<ul class="hub-backups">${d.backups.map(b => `<li><a href="${e(b.url)}" download>${e(b.name)} </a><small>${e(date(b.at))} · ${(b.size/1048576).toFixed(2)} MB</small></li>`).join("")}</ul>` : empty("No catalogue backups found.")}`, "hub-wide")}${card("Restore catalogue backup", `<p>Restore is conflict-aware. A normal restore reports changed files and makes no changes; replacement requires an explicit choice and creates a safety backup first.</p><form data-hub-form="restore-backup"><label>Backup<select name="archive" required>${(d?.backups || []).map(b => `<option value="${e(b.name)}">${e(b.name)}</option>`).join("")}</select></label><label class="hub-check"><input type="checkbox" name="replace"> Replace conflicting files</label><button class="primary">Review restore</button></form>`, "hub-wide")}${card("Browser data", `<p>Export your profile, preferences, presets, and saved personas to a local JSON file.</p><div class="hub-actions">${button("export-browser","Export browser data")}<button data-hub-action="import-browser">Import browser data</button><input id="browser-import-file" type="file" accept="application/json,.json" hidden></div><p class="muted">Imported persona IDs are never overwritten; collisions receive an import suffix and variant parents are remapped when both records are present.</p>`)}${card("Import catalogue entries", `<p>Use Pool editor for a reviewed entry import with server-side validation, duplicate detection, and automatic backup.</p>${route("editor", "Open Pool editor")}`, "hub-full")}</div>`;
  if (page === "diagnostics") return `${card("Latest audit", (d ? healthSummary(d.audit) : empty("Audit data is not connected yet.")) + `<div class="hub-actions">${button("audit","Run health audit",'class="primary"')}${route("forge","Explore coverage")}</div><p class="muted">Uses Populator scan_health, including schema validation and similarity detection. Similarity warnings are not automatically considered intentional. Tests are not run by this audit.</p>`)}${d?.audit ? card("Findings", `<p class="muted">Audit snapshot from ${e(date(d.audit.at))}. Rerun after catalogue changes.</p>${d.audit.findings.length ? `<div class="hub-findings">${d.audit.findings.map(f => `<details><summary><span class="hub-badge">${e(f.severity)}</span> ${e(f.code)} · ${e(f.message)}</summary><p>${e((f.entry_ids || []).join(", "))}</p>${f.category ? route(`forge/${encodeURIComponent(`catalogue:${f.category}`)}`,"Inspect affected catalogue") : ""}</details>`).join("")}</div>` : empty("No findings.")}`) : ""}`;
  if (page === "about") return card("Prompt Forge", `<p class="hub-lead">A local creative studio, powered by PersonaForge.</p><dl class="hub-definition">${Object.entries(d?.versions || {}).map(([k,v]) => `<dt>${e(k.replaceAll("_"," "))}</dt><dd>${e(v)}</dd>`).join("")}</dl><p class="muted">Version metadata is read from the application, data, schema, and package files. No build identifier is published by this checkout.</p><div class="hub-actions"><a href="/README.md" target="_blank">Documentation ↗</a><a href="/NARRATIVE_STABILIZATION_v0.4.1.md" target="_blank">Latest milestone notes ↗</a></div>`, "hub-form-card");
  return empty("Choose a Control Centre page.");
}

