import { createReference, resolveReference, validateReference } from "./reference-model.js";
import { getLocationType } from "./location-types.js";
export const LOCATION_KEY = "personaforge.locations.v1";
export const LOCATION_SCHEMA_VERSION = 1;
const now = () => new Date().toISOString();
const clean = (value, limit = 300) => String(value ?? "").trim().slice(0, limit);
const object = value => value && typeof value === "object" && !Array.isArray(value) ? value : {};
const makeId = () => `location_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
const validRef = (value, type) => { const checked = validateReference(value); return checked.state === "valid" && checked.reference.type === type ? checked.reference : null; };
export function normalizeLocation(raw = {}) { const source = object(raw), createdAt = typeof source.createdAt === "string" ? source.createdAt : now(); return { schemaVersion: LOCATION_SCHEMA_VERSION, id: clean(source.id || makeId(), 160) || makeId(), projectRef: validRef(source.projectRef, "project"), name: clean(source.name || "Untitled Location", 160) || "Untitled Location", type: clean(source.type, 60) || "other", description: clean(source.description, 2000), geography: structuredClone(object(source.geography)), environment: structuredClone(object(source.environment)), parentRef: validRef(source.parentRef, "location"), workspace: structuredClone(object(source.workspace)), createdAt, modifiedAt: typeof source.modifiedAt === "string" ? source.modifiedAt : createdAt, provenance: structuredClone(object(source.provenance?.kind ? source.provenance : { kind: "manual" })) }; }
export function validateLocation(raw) { const issues = []; if (!raw || typeof raw !== "object" || Array.isArray(raw)) return { valid: false, issues: ["Location must be an object."], value: null }; if (typeof raw.id !== "string" || !raw.id.trim()) issues.push("id is required"); if (typeof raw.name !== "string" || !raw.name.trim()) issues.push("name is required"); if (raw.type !== undefined && !getLocationType(raw.type)) issues.push("unknown location type"); if (raw.projectRef && !validRef(raw.projectRef, "project")) issues.push("projectRef must be a project reference"); if (raw.parentRef && !validRef(raw.parentRef, "location")) issues.push("parentRef must be a location reference"); return { valid: !issues.length, issues, value: issues.length ? null : normalizeLocation(raw) }; }
function createsCycle(id, parentRef, items) { let cursor = parentRef?.id, seen = new Set([id]); while (cursor) { if (seen.has(cursor)) return true; seen.add(cursor); cursor = items.find(item => item.id === cursor)?.parentRef?.id; } return false; }
export class LocationStore {
  constructor(storage = globalThis.localStorage) { this.storage = storage; }
  rawAll() { try { const value = JSON.parse(this.storage.getItem(LOCATION_KEY) || "[]"); return Array.isArray(value) ? value : []; } catch { return []; } }
  all() { return this.rawAll().filter(item => validateLocation(item).valid).map(normalizeLocation); }
  write(items) { this.storage.setItem(LOCATION_KEY, JSON.stringify(items.map(normalizeLocation))); }
  open(id) { return this.all().find(item => item.id === id) || null; }
  create(fields = {}) { const items = this.all(), stamp = now(), item = normalizeLocation({ ...fields, id: fields.id || makeId(), createdAt: stamp, modifiedAt: stamp }); if (!getLocationType(item.type) || createsCycle(item.id, item.parentRef, items)) throw new Error("Invalid location type or parent hierarchy."); this.write([item, ...items]); return item; }
  update(id, patch = {}) { const items = this.all(), index = items.findIndex(item => item.id === id); if (index < 0) return null; const item = normalizeLocation({ ...items[index], ...patch, id, createdAt: items[index].createdAt, modifiedAt: now() }); if (!getLocationType(item.type) || createsCycle(id, item.parentRef, items.filter(value => value.id !== id))) throw new Error("Invalid location type or parent hierarchy."); items[index] = item; this.write(items); return item; }
  delete(id) { const items = this.all(), next = items.filter(item => item.id !== id); if (next.length === items.length) return false; this.write(next); return true; }
  ancestry(id) { const items = this.all(), result = [], seen = new Set(); let current = items.find(item => item.id === id); while (current && !seen.has(current.id)) { result.unshift(current); seen.add(current.id); current = items.find(item => item.id === current.parentRef?.id); } return result; }
  browserData() { return { locations: this.all(), locationSchemaVersion: LOCATION_SCHEMA_VERSION }; }
  importBrowserData(snapshot, { collision = "rename", projectMap = {}, locationMap = {} } = {}) { const incoming = Array.isArray(snapshot?.locations) ? snapshot.locations : [], used = new Set(this.all().map(item => item.id)), idMap = {}, pending = []; for (const raw of incoming) { const checked = validateLocation(raw); if (!checked.valid) continue; const item = checked.value, original = item.id; if (item.projectRef?.id && projectMap[item.projectRef.id]) item.projectRef = { ...item.projectRef, id: projectMap[item.projectRef.id] }; if (used.has(item.id)) { if (collision !== "rename") continue; let n = 1; while (used.has(`${item.id}_import_${n}`)) n++; item.id = `${item.id}_import_${n}`; } used.add(item.id); idMap[original] = item.id; pending.push(item); } for (const item of pending) if (item.parentRef?.id) item.parentRef = { ...item.parentRef, id: idMap[item.parentRef.id] || locationMap[item.parentRef.id] || item.parentRef.id }; this.write([...pending, ...this.all()]); return { imported: pending.length, skipped: incoming.length - pending.length, idMap, renamed: Object.entries(idMap).filter(([from, to]) => from !== to).map(([from, to]) => ({ from, to })) }; }
  diagnostics(projects = []) { const raw = this.rawAll(), projectIds = new Set(projects.map(item => item.id)), ids = new Set(raw.map(item => item?.id).filter(Boolean)), duplicateIds = raw.filter((item, index) => item?.id && raw.findIndex(value => value?.id === item.id) !== index).map(item => item.id), valid = raw.filter(item => validateLocation(item).valid), missingParents = raw.filter(item => item?.parentRef?.id && !ids.has(item.parentRef.id)).map(item => item.id), malformedParents = raw.filter(item => item?.parentRef && !validRef(item.parentRef, "location")).map(item => item.id), selfParents = raw.filter(item => item?.id && item.parentRef?.id === item.id).map(item => item.id), cycles = valid.filter(item => createsCycle(item.id, item.parentRef, valid)).map(item => item.id); return { total: raw.length, valid: valid.length, invalidRecords: raw.length - valid.length, fullyResolved: valid.filter(item => (!item.projectRef || projectIds.has(item.projectRef.id)) && (!item.parentRef || ids.has(item.parentRef.id))).length, missingProjectRefs: raw.filter(item => item?.projectRef?.id && !projectIds.has(item.projectRef.id)).map(item => item.id), missingParentRefs: missingParents, malformedParentRefs: malformedParents, selfParentIds: selfParents, hierarchyCycles: [...new Set(cycles)], unknownTypes: raw.filter(item => item?.type && !getLocationType(item.type)).map(item => item.id), duplicateIds }; }
}
