const definitions = [
  ["parent", "Parent", true, "child", "family"], ["child", "Child", true, "parent", "family"], ["sibling", "Sibling", false, null, "family"], ["spouse", "Spouse", false, null, "family"], ["partner", "Partner", false, null, "family"], ["relative", "Relative", false, null, "family"],
  ["friend", "Friend", false, null, "social"], ["close_friend", "Close friend", false, null, "social"], ["acquaintance", "Acquaintance", false, null, "social"], ["mentor", "Mentor", true, "mentee", "social"], ["mentee", "Mentee", true, "mentor", "social"],
  ["colleague", "Colleague", false, null, "professional"], ["manager", "Manager", true, "subordinate", "professional"], ["subordinate", "Subordinate", true, "manager", "professional"], ["teacher", "Teacher", true, "student", "professional"], ["student", "Student", true, "teacher", "professional"], ["teammate", "Teammate", false, null, "professional"],
  ["rival", "Rival", false, null, "adversarial"], ["enemy", "Enemy", false, null, "adversarial"], ["competitor", "Competitor", false, null, "adversarial"], ["romantic_interest", "Romantic interest", false, null, "romantic"], ["dating", "Dating", false, null, "romantic"], ["former_partner", "Former partner", false, null, "romantic"], ["associate", "Associate", false, null, "flexible"], ["other", "Other", false, null, "flexible"]
];
export const RELATIONSHIP_TYPES = Object.freeze(Object.fromEntries(definitions.map(([id,label,directional,inverse,category]) => [id, Object.freeze({id,label,directional,inverse,category})])));
export const RELATIONSHIP_STATUSES = Object.freeze(["active", "former", "estranged", "deceased", "complicated", "unknown"]);
export const getRelationshipType = id => RELATIONSHIP_TYPES[id] || null;
export const relationshipLabel = id => RELATIONSHIP_TYPES[id]?.label || String(id || "Unknown relationship");
export const inverseRelationshipType = id => RELATIONSHIP_TYPES[id]?.inverse ? RELATIONSHIP_TYPES[RELATIONSHIP_TYPES[id].inverse] : null;
export const isSymmetricRelationship = id => RELATIONSHIP_TYPES[id] ? !RELATIONSHIP_TYPES[id].directional : false;
export function canonicalRelationshipKey(type, sourceId, targetId) { const def = getRelationshipType(type); if (!def || !sourceId || !targetId) return null; if (def.directional && def.inverse) { const canonicalType = [type, def.inverse].sort()[0], source = type === canonicalType ? sourceId : targetId, target = type === canonicalType ? targetId : sourceId; return `${canonicalType}:${source}:${target}`; } if (def.directional) return `${type}:${sourceId}:${targetId}`; const [left,right] = [sourceId,targetId].sort(); return `${type}:${left}:${right}`; }
export function relationshipEquivalent(a,b) { if (!a || !b || a.type !== b.type && getRelationshipType(a.type)?.inverse !== b.type && getRelationshipType(b.type)?.inverse !== a.type) return false; return canonicalRelationshipKey(a.type,a.sourceRef?.id,a.targetRef?.id) === canonicalRelationshipKey(b.type,b.sourceRef?.id,b.targetRef?.id); }
